{% set name = "akamai" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/akamai/cli/archive/v{{ version }}.tar.gz
  sha256: aa51202c2be133d10c9a34e942749c1359f9e6a4ba6f121d37f05c917d0acde7

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - akamai --help

about:
  home: https://github.com/akamai/cli
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: CLI toolkit for working with Akamai's APIs
  dev_url: https://github.com/akamai/cli

extra:
  recipe-maintainers:
    - danielnachun
