schema_version: 1

context:
  version: "2.0.4"

package:
  name: akamai
  version: ${{ version }}

source:
  url: https://github.com/akamai/cli/archive/v${{ version }}.tar.gz
  sha256: 5f0d5217e3434fc57bfc821519379a1705ed749ae754853ea1d40ff65e21eb69

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - akamai --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - license-files/
  summary: CLI toolkit for working with Akamai's APIs
  homepage: https://github.com/akamai/cli
  repository: https://github.com/akamai/cli

extra:
  recipe-maintainers:
    - danielnachun
